site_name: JW Platform Developer Guide
theme: jwplayer
site_dir: developer-guide
repo_url: https://github.com/jwplayer/jwplatform-docs
site_favicon: http://www.jwplayer.com/wp-content/themes/jwplayer-20/assets/images/favicon.ico
pages:
    - Introduction: 'index.md'
    - Embedding Players: 'building_your_site/embedding_players.md'
    - Recommended Feeds Widgets: 'building_your_site/recommended_feeds_widgets.md'
    - Uploading Videos: 'integrating_with_your_cms/uploading_videos.md'
    - Batch Migrations: 'integrating_with_your_cms/batch_migration.md'
    - Release Notes: 'release-notes.md'
